---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: nav-enonicxp-dev-proxy
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  team: personbruker
  port: 1337
  liveness:
    path: /internal/isAlive
    initialDelay: 5
  readiness:
    path: /internal/isReady
    initialDelay: 5
  ingresses:
     - https://nav-enonicxp-proxy.intern.dev.nav.no
  env:
    - name: NPM_CONFIG_CACHE
      value: /tmp/npm-cache
  filesFrom:
    - secret: nav-enonicxp-dev1
      mountPath: /var/secrets/dev1
    - secret: nav-enonicxp-dev2
      mountPath: /var/secrets/dev2
  replicas:
    min: 1
    max: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
