---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: nav-enonicxp-dev-proxy
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  team: personbruker
  port: 1337
  liveness:
    path: /internal/isAlive
    initialDelay: 5
  readiness:
    path: /internal/isReady
    initialDelay: 5
  ingresses:
     - {{url}}
  env:
    - name: NPM_CONFIG_CACHE
      value: /tmp/npm-cache
  replicas:
    min: 1
    max: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
