name: Deploy to dev
on: workflow_dispatch

jobs:
    build-and-deploy:
        uses: ./.github/workflows/build-image.yml
        permissions:
            contents: read
            id-token: write
        with:
            environment: dev
            app_origin: 'https://www.ansatt.dev.nav.no'
        secrets:
            NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

    deploy_dev:
        name: Deploy to dev
        runs-on: ubuntu-latest
        needs: build-and-deploy
        permissions:
            contents: read
            id-token: write
        steps:
            - name: Deploy to nais
              uses: nais/deploy/actions/deploy@v2
              env:
                  CLUSTER: dev-gcp
                  VAR: image=${{ needs.build_image.outputs.image }}
                  VARS: .nais/vars-dev.yml
                  RESOURCE: .nais/config.yml
